#Kotlin
kotlin.code.style=official
# Slightly reduce Kotlin daemon RAM to protect the total 16GB available.
# Add ParallelGC to leverage multiple cores of the M1 Pro during garbage collection.
kotlin.daemon.jvmargs=-Xmx2g -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
kotlin.incremental.native=true

#Gradle
# We optimize the Garbage Collector and limit Metaspace to prevent memory leaks between compilations.
org.gradle.jvmargs=-Xmx3g -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
# Ref: https://touchlab.co/optimizing-gradle-builds-in-Multi-module-projects#enable-gradle-parallel-execution
org.gradle.parallel=true
org.gradle.workers.max=6
# Ensures fast response times in macOS file system.
org.gradle.vfs.watch=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Since all dependencies are on AndroidX, we can safely disable Jetifier to improve build performance.
android.enableJetifier=false
# https://developer.android.com/build/releases/agp-9-0-0-release-notes?hl=es-419
android.newDsl=true